### ISSUE TITLE
HiSim这个项目现在还可以正常运行吗

### ISSUE THREAD

**Issue by Eastup123** [xymou/HiSim#2]
请问一下，HiSim这个项目现在还可以正常运行吗，我测试gpt-3.5-turbo-0613显示已经被弃用（gpt-3.5-turbo-0613 has been deprecated），想问一下本项目是否更新了。

**Comment by xymou** [comment]
Hi！如果gpt-3.5-turbo-0613已弃用，可以换其他的可用模型进行模拟，agent生成的内容会不一样，但不影响模拟框架的运行。考虑到模拟成本，本项目暂时没有用最新的模型重新模拟的结果。
